### PR TITLE
remove Pylibmc reference in cryptography comment

### PR DESCRIPTION
**Pull request by whit537**

### CODE REVIEW

**Comment by kennethreitz** [comment]
Either is fine. Technically, the file should be rennamed and the comment should remain the same.

**Comment by kennethreitz** [comment]
OH it says "Pylibmc" :P

**Comment by whit537** [comment]
Yeah, presumably it was an artifact of copying/pasting/editing [`bin/steps/pylibmc`](https://github.com/whit537/heroku-buildpack-python/blob/e4aa40216bd55197040ba2fa4729c7289f09add0/bin/steps/pylibmc).

👍

**Comment by kennethreitz** [comment]
@whit537 ❤️ <-- die for penny-defacer

**Pull request merged**
