### PR TITLE
Add CPython 3.6.5

### LINKED ISSUE #674: New release (python:python:3.6.5) available! (Herald System)
This issue created programmatically and automatically by Heroku, on behalf of kennethreitz, the owner of the python buildpack.

### PR DESCRIPTION
**Pull request by joshfriend**
fixes #674

### CODE REVIEW

**Comment by joshfriend** [comment]
@edmorley done, sorry! I forgot to check that this time 😛

**Comment by edmorley** [comment]
@kennethreitz, ping for review? :-)

**Comment by kennethreitz** [comment]
Thanks for opening this issue! Will try to get this merged/released today. 

One question — is the formula `chmod +x`'d?

**Comment by kennethreitz** [comment]
It won't work otherwise :)

**Comment by joshfriend** [comment]
@kennethreitz yes it is 😉 @edmorley caught that and reminded me!

> new file mode 100755

https://patch-diff.githubusercontent.com/raw/heroku/heroku-buildpack-python/pull/676.diff

**Comment by joshfriend** [comment]
I wonder how hard it would be to add a simple test that runs on travis to verify the permissions of these files.

**Pull request merged**
