### PR TITLE
Bump pipenv version

### PR DESCRIPTION
**Pull request by allyjweir**
We are depending on some of the bug fixes released between the last version and 11.10.4 (VCS package related issues). Having updated locally for our dev envrionments, thought it was worthwhile to bump the version in the buildpack in use too.

### CODE REVIEW

**Comment by allyjweir** [comment]
Tests are failing on Travis: 
```
testPipenvLock
ASSERT:Captured exit code - expected:<0> but was:<1>
-----> Installing python-3.6.5
-----> Installing pip
-----> Installing dependencies with Pipenv 11.10.4…
       Your Pipfile.lock (d26635) is out of date. Expected: (00ad98).
       Aborting deploy.
```

I went into the fixtures for the failing test and tried running `pipenv lock` to regenerate the `Pipenv.lock` file. Unfortunately this didn't generate a new lockfile with the required hash. @kennethreitz (or any other maintainer with pipenv experience!), any advice on how to resolve this issue? 

Thanks in advance.

**Comment by kennethreitz** [comment]
that should do the trick!

**Comment by allyjweir** [comment]
Figured out my issue. My local install of `pipenv` wasn't at latest version so was getting different hash when running `pipenv lock` using my local machine.

Now getting a shellcheck failure on Travis but not locally. Will update as I progress...

**Comment by sigmavirus24** [comment]
@hone this looks good to me. I updated the branch so it would merge cleanly. (I had missed that @allyjweir had fixed the shellcheck violations.) Would you mind giving this a look over as well for compliance?

**Comment by allyjweir** [comment]
What's the process for this becoming in use in Heroku dynos?

**Comment by KevinBrolly** [comment]
@allyjweir This pull request was release with V135 so it is now available to run on your dynos, next time you do a build it should pick up the new version.

P.S I also used to work at Twig, say hi to everyone for me!

**Pull request merged**
