### PR TITLE
Add support for PIP_EXTRA_INDEX_URL

### PR DESCRIPTION
**Pull request by p-himik**
Akin to #363 but exports only `PIP_EXTRA_INDEX_URL` so users don't have to store possibly sensitive extra index URL in their repository code.

### CODE REVIEW

**Comment by kennethreitz** [comment]
in order to merge this, though, you must pass shellcheck standards:

https://travis-ci.org/heroku/heroku-buildpack-python/jobs/341306525

**Comment by kennethreitz** [comment]
I would also recommend moving this to the `pip-install` step.

**Comment by williammcbroom** [comment]
I'm the author of the original PR #363 and the main reason for my changes was to get the `PIP_EXTRA_INDEX_URL` environment variable set too. @p-himik thank you for making a new PR and I hope you can get it merged in.

**Comment by p-himik** [comment]
@kennethreitz Fixed spellcheck errors, moved the code to the `pip-install` step.

**Pull request merged**
