### PR TITLE
Fix PYTHONPATH is not set when running collectstatic

### PR DESCRIPTION
**Pull request by jxltom**
In command ```bin/steps/collectstatic```, PYTHONPATH is not set.

If manage.py file is not located at root folder but in the subfolder of a project and if ```import some_module_in_project``` is called in ```manage.py```, ```python somefolder/manage.py collectstatic --noinput``` will raise ```can not find module``` error. This is due to ```PYTHONPATH``` is not set for root folder and python can not import project's own module.

### CODE REVIEW

**Comment by jxltom** [comment]
I found this issue because I have a customized ```manage.py``` which will do some additional work for me. But this ```manage.py``` needs import some modules of the project and since PYTHONPATH is not set, ```python manage.py collectstatic``` will raise can not find module error

Here is the project layout

```
Procfile
requirements.txt
myapplication
    manage.py
    settings.py
    ....other...stuff...
```

**Comment by kennethreitz** [comment]
thanks!

**Comment by jxltom** [comment]
Glad to contribute!

**Comment by jxltom** [comment]
@kennethreitz It looks like buildpack in Heroku is cached. May I know how can I update the buildpack in Heroku? It looks like the buildpack is not using the latest one in github even I create a new project in Heroku

**Comment by edmorley** [comment]
The `heroku/python` buildpack alias maps to stable releases rather than master of this repo. The versions/release dates can be seen using:
https://github.com/heroku/heroku-buildkits#revisions

In the meantime if you wish to use master, set the buildpack URL to this git repository like so:
https://devcenter.heroku.com/articles/buildpacks#using-a-third-party-buildpack

**Pull request merged**
