### PR TITLE
Python 3 default for buildpack

### PR DESCRIPTION
**Pull request by kennethreitz**
This is planned to roll out on June 20th.

### CODE REVIEW

**Comment by edmorley** [comment]
Regarding the nltk test failures, all I can find is:
https://github.com/nltk/nltk/issues/1696
https://groups.google.com/d/msg/nltk-users/Ns_02i8WOtc/UNMD524KEgAJ

...which aren't much help :-(

**Comment by edmorley** [comment]
Perhaps the tests should be run on both Python 2.x and 3.x, and the test just skipped on 3.x for now?

**Comment by kennethreitz** [comment]
Yeah I'm thinking of just having that test run on 2.7 explicitly.

**Comment by kennethreitz** [comment]
Done :)

**Comment by kennethreitz** [comment]
Changelog announced: https://devcenter.heroku.com/changelog-items/1169

**Comment by kennethreitz** [comment]
Waiting for builds to pass, then merging!

**Comment by edmorley** [comment]
When you release this, could you also add the tag for v109? I think it was 04f3ddbc86f6e5419fc247de268e5a1bfb0a00c3.

**Pull request merged**
