### PR TITLE
add python 2.7.18

### PR DESCRIPTION
**Pull request by hone**
Add support for the [last release of Python 2.7](https://pythoninsider.blogspot.com/2020/04/python-2718-last-release-of-python-2.html).

### CODE REVIEW

**Comment by edmorley** [comment]
During #968 I noticed that the Python 3.5.9 and 3.7.7 releases are also missing. I was going to open a PR to add those, however it will conflict with this and I don't have access to the AWS creds required to generate the binaries. Does it make sense to combine the two PRs?

**Comment by edmorley** [comment]
> Does it make sense to combine the two PRs?

@hone, thoughts on this? :-)

**Comment by edmorley** [comment]
Superseded by #977.

**Comment by hone** [comment]
:+1: thanks for taking this over.

**Pull request closed without merging**
