### PR TITLE
Switch pip-pop back to using pip 8

### LINKED ISSUE #302: 'pip-diff: error: no such option: --hash' due to vendored pip 7.1.2
We're currently using the Pip hash support added in pip 8.0.

However pip-pop run during the buildpack compile is made to use an older version of pip (7.1.2) as of:
https://github.com/heroku/heroku-buildpack-python/commit/0b7a1fc14e6e0a0e694f8e8da1a2e004ef2e53a7

This results in:
```
-----> Python app detected
Usage: pip-diff [options]
Traceback (most recent call last):
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 119, in <module>
    main()
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 114, in main
    diff(**kwargs)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 85, in diff
    r1 = Requirements(r1)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 28, in __init__
    self.load(reqfile)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 39, in load
    for requirement in parse_requirements(reqfile, finder=finder, session=requests):
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 172, in process_line
    for req in parser:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 119, in process_line
    opts, _ = parser.parse_args(shlex.split(options_str), defaults)
  File "/app/.heroku/python/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/app/.heroku/python/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 238, in parser_exit
    raise RequirementsFileParseError(msg)
pip.exceptions.RequirementsFileParseError: pip-diff: error: no such option: --hash
     $ pip install -r requirements.txt
```

The fix being to add support to pip-pop for pip 8.x (kennethreitz/pip-pop#10), to then update to that upstream version of pip-pop, and then to remove the outdated vendored version of pip from the buildpack.

### PR DESCRIPTION
**Pull request by edmorley**
* Imports the upstream pip-pop fix for pip 8 support (the not yet merged kennethreitz/pip-pop#12).
* Removes the vendored pip added in https://github.com/heroku/heroku-buildpack-python/commit/0b7a1fc14e6e0a0e694f8e8da1a2e004ef2e53a7 , so pip-pop uses the buildpack default pip (v8.1.2) which is compatible with requirements files containing the new hash syntax.

Fixes #302.

### CODE REVIEW

**Comment by kennethreitz** [comment]
Those changes (and vendored pip) were added for a reason, unfortunately, when pip 8 was released. It's non-public API changed behavior around including other files (e.g. `-r otherfile.txt`).

**Comment by edmorley** [comment]
It's making kennethreitz/pip-pop#11 (and followup work to add more tests) sound even more and more important. We have a tool that's a critical part of this buildpack that has no official test coverage :-s

**Comment by edmorley** [comment]
Could you file an issue against pip-pop that explains these non-public API changes? It's hard to help out and fix things if the issue for the vendored pip rollback isn't documented anywhere. 

Many thanks :-)

**Comment by edmorley** [comment]
(For example one of my own projects happily uses `-r otherfile.txt`, so the breakage must be subtle or limited to specific cases).

**Comment by kennethreitz** [comment]
Any development for fixing/improving these things should happen here. The seperate pip-pop repo is just an installable export of what's developed for this buildpack.

**Comment by edmorley** [comment]
Could you update https://github.com/kennethreitz/pip-pop/blob/master/README.rst to that effect? :-)

**Comment by kennethreitz** [comment]
No, pip-pop itself may evolve beyond that one day. I'm saying right now, at this moment, if you want to contribute towards improving these particular features, it needs to be done here.

**Comment by edmorley** [comment]
@kennethreitz any news on this?

Without the issue mentioned above having been documented anywhere it's hard to know where to start.

I know this repo is in a grey area between "active open source project" and "source provided for primarily for reference rather than contributions" (and I know your time must be stretched pretty thinly), but I must admit the contribution process for this repo has been frustrating across the various PRs over the last few months.

> No, pip-pop itself may evolve beyond that one day. I'm saying right now, at this moment, if you want to contribute towards improving these particular features, it needs to be done here.

It would still be useful to document that in the buildpack's readme (or else in a `CONTRIBUTING.md` or in a readme in the `vendor/` directory), otherwise it just wastes contributors time when they open up PRs against the wrong repo.

**Comment by kennethreitz** [comment]
IF `-r` is working as expected now, I am going to assume it is because pip changed something to fix the situation. Again, this toolchain is using unpublic APIs to accomplish what it does, and it could change at any time — therefore, having a vendored version of pip is not a bad idea. 

If things appear to work properly with the latest version, I will consider re-vendoring that version of pip.

**Comment by kennethreitz** [comment]
Merging into master, which is a good testing ground — only people using the multibuildpack and not pinning to a specific release use master. Will have to wait a bit before shipping production. Changes may be required.

**Comment by kennethreitz** [comment]
- [ ] make sure nothing is broken for edge-case customers
- [ ] make sure `--hash` works
- [ ] update pip-pop repo
- [ ] ship to prod

**Comment by jotes** [comment]
@kennethreitz thx! :bow:

**Comment by jotes** [comment]
@kennethreitz I'm testing the master branch and pylibmc is being detected correctly. You can look at my app.json here: https://github.com/jotes/pontoon/blob/master/app.json

**Comment by kennethreitz** [comment]
\o/

**Comment by RochesterinNYC** [comment]
Small note that another category that consumes master is repos that pull downstream from this repo. The team maintaining the Cloud Foundry python buildpack is interested in pulling down these upstream changes when y'all feel that this PR/its functionality is stable.

The team's work on this is tracked at https://www.pivotaltracker.com/story/show/127892095.

**Comment by RochesterinNYC** [comment]
Just wondering, has this work been cut into a release/deployed on Heroku yet? Thanks.

**Comment by cclauss** [comment]
I read this PR as "Merged 20 days ago".

**Comment by RochesterinNYC** [comment]
It's been merged into the master of the heroku python buildpack, but as @kennethreitz stated above, it hasn't been released to production yet.

**Comment by kennethreitz** [comment]
As of 10 minutes ago, yes.

**Comment by jotes** [comment]
@kennethreitz awesome! thx for your work!

**Pull request merged**
