### PR TITLE
Add PyPy2 5.8.0

### PR DESCRIPTION
**Pull request by joshfriend**
#414 only added the pypy3 version

### CODE REVIEW

**Comment by kennethreitz** [comment]
closing and reopening to re-trigger ci builds

**Comment by kennethreitz** [comment]
thanks though, this looks solid!

**Comment by kennethreitz** [comment]
I hope this is `chmod  +x`'d!

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/bob-builder/issues/35

**Comment by joshfriend** [comment]
It should be `+x`:

```
$ ls -la builds/runtimes/pypy-5.8.0
-rwxr-xr-x@ 1 josh  staff   337B Jul 26 13:04 builds/runtimes/pypy-5.8.0*
```

Did it somehow not come out that way in the repo?

**Comment by joshfriend** [comment]
CI stalled again

**Comment by kennethreitz** [comment]
looks like nltk downloads aren't working at the moment

**Comment by kennethreitz** [comment]
Thanks so much!

**Comment by kennethreitz** [comment]
minor bug, fixed in 'pypy' branch

**Comment by kennethreitz** [comment]
Deployed! ✨🍰✨

**Pull request merged**
