### PR TITLE
Update geos to version 3.6.2

### PR DESCRIPTION
**Pull request by codingjoe**
#### Changes in 3.6.2
2017-07-25

- Bug fixes / improvements
  - Fix exception in UnaryUnion of collection of touching polygons (#837)
  - Allow building against python 3 (#774)
  - Fix build with android-ndk and other compilers (#799)
  - Allows compiling with -Wpointer-bool-conversion (#638)
  - Fix unhandled exception on invalid fp operation (#811)
  - Fix overloaded virtual print in DirectedEdge* (#812)
  - AppVeyor CI build added (#813)
  - Clean up numerous MSVC warnings, notably C4275 and C4589 (#814)
  - Bump CMake version to 3.0.0 (#817)
  - Fix leaks in WKT parser (#830)

#### Changes in 3.6.1
2016-12-24

- Bug fixes / improvements
  - Fix GEOSSTRtree_nearest_r signature and add implementation (#796)
  - Fix --static-clibs and --static-cclibs returns from geos-config
  - Fix WKB representation of empty polygon (#680).
  - Fix empty GEOSSimplify return on inner ring collapse (#741)

#### Changes in 3.6.0
2016-10-25

- Important / Breaking Changes:
  - The PHP binding moved to its own repository:
    http://git.osgeo.org/gogs/geos/php-geos (#765)
- New things:
  - CAPI: GEOSGeom_{get,set}UserData (Rashad Kanavath)
  - CAPI: GEOSGeom_{set,get}Precision (#713)
  - CAPI: GEOSMinimumRotatedRectangle and GEOSMinimumWidth
    (#729, Nyall Dawson)
  - CAPI: GEOSSTRtree_nearest (#768, Dan Baston)
  - CAPI: GEOSMinimumClearance and GEOSMinimumClearanceLine
    (#776, Dan Baston)
- C++ API changes:
  - Automatic memory management for GeometryFactory objects

#### Changes in 3.5.0
2015-08-16

- New things:
  - Voronoi API (#627)
  - PHP: Geometry->normalize method
  - GEOS_USE_ONLY_R_API macro support (#695)
  - PHP: WKBReader->read() & WKBWriter::write() methods (Benjamin Morel)
  - GEOSClipByRect (#699, Mika Heiskanen, Sandro Santilli)
  - CAPI: thread-safe message handling API (#663, Pepijn Van Eeckhoudt)
- Improvements:
  - Speed-up intersection and difference between geometries
    with small bounding box overlap.
  - CAPI: add MULTILINESTRING support for GEOSisClosed (Benjamin Morel)
- C++ API changes:
  - Added no-parameter CoordinateSequenceFactory::create method (Sandro Mani)

### CODE REVIEW

**Comment by codingjoe** [comment]
```shell
bob build libraries/vendor/goes
...
Build complete: /app/.heroku/vendor/
```
🎉

**Comment by kennethreitz** [comment]
thanks! will look at this shortly

**Comment by kennethreitz** [comment]
this one also looks good. I think i'm going to leave cedar-14 the same, and only update heroku-16.

**Comment by kennethreitz** [comment]
deployed to heroku-16

**Pull request merged**
