### PR TITLE
update python.gunicorn.sh to WEB_CONCURRENCY.sh

### PR DESCRIPTION
**Pull request by kennethreitz**

### CODE REVIEW

**Comment by hunterloftis** [comment]
should delete this: https://github.com/heroku/heroku-buildpack-python/blob/43bf220458011a4b34be0ef71b68e2279fee9f0d/vendor/WEB_CONCURRENCY.sh#L1-L4

should probably leave this in python.gunicorn.sh: https://github.com/heroku/heroku-buildpack-python/blob/43bf220458011a4b34be0ef71b68e2279fee9f0d/vendor/WEB_CONCURRENCY.sh#L37-L38

**Comment by dzuelke** [comment]
Hey that's exactly what my review said too @hunterloftis :p

**Comment by hunterloftis** [comment]
Then I guess I agree @dzuelke ;)

**Comment by kennethreitz** [comment]
@dzuelke @hunterloftis updated.

**Comment by dzuelke** [comment]
There's still Gunicorn-specific code in `WEB_CONCURRENCY.sh`, and the variable name refers to Gunicorn.

Split it into two files, @kennethreitz?

**Comment by kennethreitz** [comment]
doing that now

**Comment by dzuelke** [comment]
Now you have the file names swapped in the variable assignments @kennethreitz.

**Comment by kennethreitz** [comment]
@dzuelke you're too fast for me — fixed now :)

**Comment by kennethreitz** [comment]
Wish GitHub had a "ready for re-review" button.

**Comment by kennethreitz** [comment]
Also, note how these CI builds take forever. I found some solutions online for this — https://giorgos.sealabs.net/docker-cache-on-travis-and-docker-112.html 

worth exploring.

**Comment by kennethreitz** [comment]
#375

**Pull request merged**
