### PR TITLE
Update gdal to version 2.2.1

### PR DESCRIPTION
**Pull request by codingjoe**
[Release Notes](https://trac.osgeo.org/gdal/wiki/DownloadSource)

### CODE REVIEW

**Comment by codingjoe** [comment]
```shell
bob build libraries/vendor/gdal
...
Build complete: /app/.heroku/vendor/
```
🎉

**Comment by kennethreitz** [comment]
these are major version bumps. I'm a little wary of upgrading — are there any backwards incompatible changes?

**Comment by kennethreitz** [comment]
🤞

**Comment by kennethreitz** [comment]
waiting for builds to pass

**Comment by kennethreitz** [comment]
deployed to heroku-16

**Pull request merged**
