### PR TITLE
Codingjoe/shellcheck action

### PR DESCRIPTION
**Pull request by CaseyFaist**
Triggering #900 from privileged account, investigating why changes don't trigger travis test suite

### CODE REVIEW

**Comment by CaseyFaist** [comment]
🎉 Just a whitespace issue. Scheduled for Monday release

**Comment by codingjoe** [comment]
👍  great, hope it helps :)

**Comment by CaseyFaist** [comment]
Updating to master and retriggering tests... Nothing failed, Hatchet test just wasn't triggered for some reason 🤔

**Comment by codingjoe** [comment]
It's funny, I made some changes on my branch, but GitHub does not pick them up for this PR, maybe because you opened the PR. Anyhow, I opened a new PR with the changes #943. However, since I am not a contributor, the new action will not run unless you merge it or reopen the PR yourself.

**Comment by CaseyFaist** [comment]
Thanks for the context on new pr! 

Yep, that's exactly why - it's a real pain point for me/outside contributors right now. A solution being considered is to move Hatchet tests (the blocking factor) to a separte ci/ci pipeline that only runs on master - but current shunit tests can generate false positives, and we want master to still be trustworthy. 

Closing this in favor of #943

**Pull request closed without merging**
