### PR TITLE
Greatly simplify code copying

### PR DESCRIPTION
**Pull request by dzuelke**
A few simple Symlinks so Python and modules can find themselves in `/app/.heroku/…` are enough :)

### CODE REVIEW

**Comment by kennethreitz** [comment]
this should fix the exports too

**Comment by kennethreitz** [comment]
david will update pull request with final fix for cache bug

**Comment by dzuelke** [comment]
Confirmed working even with native packages (`psycopg2`).

**Comment by dzuelke** [comment]
Confirmed fixes Python breakage for subsequent buildpacks.

**Comment by dzuelke** [comment]
Caching is still broken right now so only the first push succeeds. Will fix.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by ojacobson** [comment]
👍 huge improvement

**Pull request merged**
