### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by nsamsami**
Included a note that the build pack supports running Django and Flask apps.

### CODE REVIEW

**Comment by nsamsami** [comment]
Addresses Issue #258

**Comment by kennethreitz** [comment]
Let's change it from "the buildpack" to "this buildpack". Then, I'll merge :)

**Comment by nsamsami** [comment]
Updated the wording! Thanks @kennethreitz

**Comment by kennethreitz** [comment]
@nsamsami thanks!

**Pull request merged**
