### PR TITLE
Runtimes: Added pypy-5.3.0

### PR DESCRIPTION
**Pull request by cclauss**
Runtimes:
* Added pypy-5.3.0
* Moved python-2.7.11rc1 to python-2.7.12rc1

### CODE REVIEW

**Comment by kennethreitz** [comment]
I think I may stop releasing the RCs. No one ever uses them.

**Comment by cclauss** [comment]
I am happy to drop the RC if you want.  I saw 11 there so I updatedi it to 12. The finals should be here in a week anyway.

**Comment by kennethreitz** [comment]
Thanks! This is on my todo list.

**Comment by cclauss** [comment]
Closed in favor of PR https://github.com/heroku/heroku-buildpack-python/pull/313

**Pull request closed without merging**
