### PR TITLE
binary builds cleanup + heroku-18 support

### PR DESCRIPTION
**Pull request by hone**
* move `Dockerfile` and `requirements.txt` into `builds/` since they're only used for binary building
* add heroku-18 `Dockerfile`

### CODE REVIEW

**Comment by kennethreitz** [comment]
requirements.txt needs to be in root

**Comment by kennethreitz** [comment]
oh nvm, pipfile exists

**Comment by vijju3335** [comment]
i cant see procfile.can you please help me sir

**Comment by vijju3335** [comment]
sir shall we use cgi here

**Comment by CaseyFaist** [comment]
hey @sigmavirus24 @hone what's the status of this? has this been addressed elsewhere, and what was the intent of this refactor?

**Comment by sigmavirus24** [comment]
🤷‍♂️ Never looked into this. I think I self-assigned and then completely forgot about it

**Comment by CaseyFaist** [comment]
Closing as this work was incorporated elsewhere

**Pull request closed without merging**
