### PR TITLE
Add support for Python 3.8.9 and 3.9.4

### PR DESCRIPTION
**Pull request by edmorley**
The upstream Python 3.8.9 and 3.9.3 releases were brought forwards by a month due to some security fixes:
https://pythoninsider.blogspot.com/2021/04/python-393-and-389-are-now-available.html

However the Python 3.9.3 release was then recalled due to an ABI compatibility issue, and replaced by Python 3.9.4:
https://pythoninsider.blogspot.com/2021/04/python-394-hotfix-is-now-available.html

For more details on Python 3.8.9 and 3.9.4, see:
https://www.python.org/downloads/release/python-389/
https://www.python.org/downloads/release/python-394/

Closes GUS-W-8159180.
Closes GUS-W-8618286.

### CODE REVIEW

**Comment by edmorley** [comment]
It's worth noting that the high severity security fixes included in these releases (the OpenSSL fixes) don't apply to us, since OpenSSL is dynamically linked, so the version from the stack image is used instead. As such this isn't as urgent, since the remaining security fixes have been categorised as "low" severity.

**Comment by amureki** [comment]
@edmorley hey Ed! Small heads up, 3.9.4 was just released:
https://discuss.python.org/t/python-3-9-4-hotfix-is-now-available/8056

**Comment by edmorley** [comment]
@amureki Hi! Yeah I was planning on adding 3.9.4 to this PR today. Good thing we didn't release 3.9.3 in this buildpack in a rush over the weekend it seems :-)

**Comment by edmorley** [comment]
The new 3.8.9 and 3.9.4 binaries have been uploaded. In a few days I'll delete the 3.9.3 archives (uploaded when I opened this PR) to prevent people from accidentally using the broken version.

**Review by Malax — APPROVED** [review]

**Comment by edmorley** [comment]
https://devcenter.heroku.com/changelog-items/2089

**Pull request merged**
