### PR TITLE
Refactor env variable handling in build steps & add docs

### PR DESCRIPTION
**Pull request by codingjoe**
Ref #760 

### Manually tested

- [x] Airflow install
- [x] GEO libs without setting the pass explicitly in Django
- [x] extra package index

### CODE REVIEW

**Comment by CaseyFaist** [comment]
Thank you for the contribution! I agree with the intent of the changes and appreciate the refactors, but won't be moving forward with this PR for a couple of reasons.

First, I'm currently planning some significant restructuring in the coming months. Since the proposed changes could likely have edge case effects I'd need to find, test for and document, it's not efficient to invest the time to vet these updates for potential side effects when the surrounding processes themselves could be overhauled somewhat soon.

For the documentation updates, keeping documentation in comments by the implementation is not ideal. Comments are important for context on the code decisions, but anyone looking for a user-friendly feature list will not have a good experience if features are documented only where they are implemented. Different options are being considered to solve this problem, but no decision as of yet.

**Comment by codingjoe** [comment]
> Thank you for the contribution! I agree with the intent of the changes and appreciate the refactors, but won't be moving forward with this PR for a couple of reasons.

Sure, as you wish.

> First, I'm currently planning some significant restructuring in the coming months. Since the proposed changes could likely have edge case effects I'd need to find, test for and document, it's not efficient to invest the time to vet these updates for potential side effects when the surrounding processes themselves could be overhauled somewhat soon.

That sounds exciting I can't wait!

> For the documentation updates, keeping documentation in comments by the implementation is not ideal. Comments are important for context on the code decisions, but anyone looking for a user-friendly feature list will not have a good experience if features are documented only where they are implemented. Different options are being considered to solve this problem, but no decision as of yet.

I did add the documentation to the readme, as I obviously can't edit the articles in the Heroku knowledbge base. I do agree tho. Good point.

One last thing:
I would recommend to move ahead with 735663e tho. It is simply fixing a bug that has been effecting everyone using Django and PostGIS. See #398.

thanks joe

**Comment by codingjoe** [comment]
I could open up another PR maybe also change they way I import the environment variable to how it is done in some other places? What do you think?

**Comment by CaseyFaist** [comment]
Re: env vars - I'm planning on reviewing how the buildpack accesses environment variables, with this bit from the Node buildpack under consideration as a possible direction: https://github.com/heroku/heroku-buildpack-nodejs/blob/7df64870c0cbc1d08c3f83bd5060c5d522126729/lib/environment.sh#L52

In the short term, my focus is going to be on expanding test coverage - but if you could pull out the bugfix and wouldn't mind updating the environment variable import to match other env var loads to make the planned refactor easier, that'd definitely be worth investigating for me. Thanks for responding! I appreciate your patience while I get up to speed with the issue you linked 👍 👍 👍

**Comment by codingjoe** [comment]
> In the short term, my focus is going to be on expanding test coverage - but if you could pull out the bugfix and wouldn't mind updating the environment variable import to match other env var loads to make the planned refactor easier, that'd definitely be worth investigating for me. Thanks for responding! I appreciate your patience while I get up to speed with the issue you linked 👍 👍 👍

My pleasure, done #770 

More tests would certainly be great. Might I make a bold suggestions? Why are all buildpacks written in Bash not Python? Python is installed on [all images anyways](https://devcenter.heroku.com/articles/stack-packages) since Ubuntu switched may launch scripts from Bash to Python a long time ago. Maybe this is a path worth setting into? Testing python is certainly more rewarding than bash, don't you agree?

**Pull request closed without merging**
